spring:
  profiles:
    active: dev

---

spring:
  profiles: dev

  server:
    port: 8080

  h2:
    console:
      enabled: true
      path : /db_test   # {server_ip:server_port}/db_test 접속해서 콘솔 사용 가능

  datasource:
    #url: jdbc:h2:mem:/~/project1/src/main/resources/devdb
    url: jdbc:h2:tcp://localhost/~/project1/src/main/resources/devdb  # 서버 구동시
    username: dev
    password:
    driver-class-name: org.h2.Driver
    mapper-location: classpath:/mapper/*.xml

  jpa:
    hibernate:
      ddl-auto: update  # 어플리케이션 실행 시 테이블 Drop, 재생성
    properties:
      hibernate:
        format_sql: true
        show_sql: true  # Query 출력

  #sql:
  #  init:
  #    mode: always
  #    schema-locations: classpath:/schema/user.sql

---

spring:
  profiles: prod
  
  server:
    port: 8081

  datasource:
    url: jdbc:mysql:tcp:/175.124.235.190:8961
    username: 'youngmon.dev'
    password: 'devpwd'
    driver-class-name: org.mysql.Driver
